### ISSUE TITLE
Can not connect to gmail account

### ISSUE THREAD

**Issue by shotikot** [manyuanrong/deno-smtp#15]
Hello, I'm trying to connect my gmail account with gmail smtp but i get this error:
```
error: Uncaught ConnectionRefused: No connection could be made because the target machine actively refused it. (os error 10061)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.connectTls ($deno$/tls.ts:20:15)
    at async SmtpClient.connectTLS (https://deno.land/x/smtp/smtp.ts:36:18)`
Here's the code I use (similar to docs).
```
```
import { SmtpClient } from "https://deno.land/x/smtp/mod.ts";

const client = new SmtpClient();

await client.connectTLS({
  host: "smtp.gmail.com",
  port: 465,
  username: "my gmail",
  password: "my password",
});
```

**Comment by and2352000** [comment]
Change host to hostname

**Comment by manyuanrong** [comment]
>   host: "smtp.gmail.com"

V

>   hostname: "smtp.gmail.com"
