### ISSUE TITLE
Error while using microsoft email for smtp

### ISSUE THREAD

**Issue by KotadiyaHiral** [manyuanrong/deno-smtp#46]
Working fine with my Gmail credentials. 
I used the following credentials: 
For more port info click [here](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353)
```
await client.connectTLS({
        hostname: "smtp.office365.com",
        port: 587,
        username: "***@mydomain.com",
        password: "*********"
});
```
Error: 

```
DenoStdInternalError: bufio: caught error from `readSlice()` without `partial` property
    at assert (https://deno.land/std@0.81.0/_util/assert.ts:13:11)
    at BufReader.readLine (https://deno.land/std@0.81.0/io/bufio.ts:254:7)
    at async TextProtoReader.readLineSlice (https://deno.land/std@0.81.0/textproto/mod.ts:131:17)
    at async TextProtoReader.readLine (https://deno.land/std@0.81.0/textproto/mod.ts:33:15)
    at async SmtpClient.readCmd (https://deno.land/x/smtp@v0.7.0/smtp.ts:151:20)
    at async SmtpClient._connect (https://deno.land/x/smtp@v0.7.0/smtp.ts:118:21)
    at async SmtpClient.connectTLS (https://deno.land/x/smtp@v0.7.0/smtp.ts:68:5)
```

**Comment by KentriLuigi** [comment]
Hi there,

I have the same error but with the OVH domain using `ssl0.ovh.net` as hostname.
Do you find a workaround ?

**Comment by KotadiyaHiral** [comment]
Hi @KentriLuigi ,
No, I am not able to solve this issue yet.

**Comment by KentriLuigi** [comment]
@KotadiyaHiral 
I found a workaround using ["Send email as"](https://support.google.com/mail/answer/22370?hl=en) functionnality from gmail (but you need a gmail account, oubviously).
It's not ideal, but it's working fine with my custom domain.

**Comment by Sandroggy** [comment]
> @KotadiyaHiral I found a workaround using ["Send email as"](https://support.google.com/mail/answer/22370?hl=en) functionnality from gmail, with the gmail settings but with my address as sender / from. It's not ideal, but it's working fine with my custom domain.

You can also use the non secure method `client.connect()`
For OVH you just need to change the port: 
```
{
    hostname: "ssl0.ovh.net",
    port: 587,
    username: "mail@domain.com",
    password: "***********",
}
```

**Comment by craibuc** [comment]
Can confirm the issue is still present with Office 365, using the settings listed by @hiral-kotadiya.

Using `client.connect()` is not an option:

```javascript
await client.connect({
        hostname: "smtp.office365.com",
        port: 587,
        username: "***@mydomain.com",
        password: "*********"
});
```

> TimedOut: Operation timed out (os error 60)
    at async Object.connect (ext:deno_net/01_net.js:480:55)
    at async SmtpClient.connect (https://deno.land/x/smtp@v0.7.0/smtp.ts:56:18)
    at async file:///Users/X/Developer/javascript/deno-windmill/main.ts:28:5 {
  name: "TimedOut",
  code: "ETIMEDOUT"
}

**Comment by suchislife801** [comment]
I'm going to clarify this for you. The following services **don't just work with the same password you use to login to them**. So App specific passwords were created to **allow you to use email clients that don't support OAUTH 2.0**.

Guess what Google, Microsoft, Yahoo & AOL use by default? OAUTH 2.0.

![sample](https://github.com/manyuanrong/deno-smtp/assets/6699482/fab628b8-cc70-4d59-9fb0-28d4be2060cd)

This means you first need to generate an APP SPECIFIC PASSWORD, and then USE THIS APP SPECIFIC PASSWORD with this Deno SMTP library. Or with any email client that does not support oAUTH 2,0.

Take a look at the following links for how to generate this APP SPECIFIC PASSWORD.

[Microsoft 365 - Manage app passwords for two-step verification](https://support.microsoft.com/en-us/account-billing/manage-app-passwords-for-two-step-verification-d6dc8c6d-4bf7-4851-ad95-6d07799387e9)

[Google Gmail - Manage app passwords for two-step verification](https://support.google.com/accounts/answer/185833?hl=en)

[Yahoo Mail - Generate and manage third-party app passwords](https://help.yahoo.com/kb/SLN15241.html)

[AOL - Create and manage third-party app passwords](https://help.aol.com/articles/Create-and-manage-app-password)

[iCloud - Using app-specific passwords](https://support.apple.com/en-us/102654)

**Comment by craibuc** [comment]
I added an app-specific password (ASP) for Office 365, using the method listed the the first link.  I'm still getting the same error message.  I'm assuming that I should be using the same email address as the account used to create the ASP.

What am I not understanding?

**Comment by suchislife801** [comment]
For Outlook I have the following settings:

### Outlook account (TERRIBLE SUPPORT FOR CRLF)
```txt
protocol: "STARTTLS"
auth: "LOGIN"
hostname: "smtp-mail.outlook.com"
port: 587
username: "myusername@outlook.com"
password: "tyvslvnidbwfelar"
```

### Gmail account (FREE, SECURE, HIGHLY RELIABLE)

```txt
protocol: "TLS"
auth: "PLAIN"
hostname: "smtp.gmail.com"
port: 465
username: "myusername@gmail.com"
password: "oswwgfmqqrmujhth"
```

### Yahoo account (FREE, SECURE, NOT RELIABLE)
```txt
protocol: "STARTTLS"
auth: "LOGIN"
hostname: "smtp.mail.yahoo.com"
port: 587
username: "myusername@yahoo.com"
password: "yxfhgumeahrtpesw"
```

### AOL account (FREE, SECURE, NOT RELIABLE)

```txt
protocol: "STARTTLS"
auth: "LOGIN"
hostname: "smtp.aol.com"
port: 587
username:  "myusername@aol.com"
password: "efgmzisytrdfmiow"

```

### iCloud account (FREE, SECURE, HIGHLY RELIABLE)

```txt
protocol: "STARTTLS"
auth: "LOGIN"
hostname: "smtp.mail.me.com"
port: 587
username: "myusername@icloud.com"
password: "jdsr-mers-fbjhl-meak"
```
